### ISSUE TITLE
irc adaptor not working with 2.2.0

### ISSUE THREAD

**Issue by stuartf** [hubotio/hubot#289]
I'm not sure if this is a bug in the adaptor or hubot, or (most likely?) my own error. But hubot won't start here's the log:

```
2012-05-15T19:07:41+00:00 heroku[web.1]: Starting process with command `bin/hubot -a irc -n sakai-bot`
2012-05-15T19:07:42+00:00 app[web.1]: [Tue May 15 2012 19:07:42 GMT+0000 (UTC)] ERROR Cannot load adapter irc - Error: Cannot find module 'hubot'
2012-05-15T19:07:42+00:00 app[web.1]: TypeError: Cannot call method 'on' of null
2012-05-15T19:07:42+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/hubot:105:19)
2012-05-15T19:07:42+00:00 app[web.1]:     at /app/node_modules/coffee-script/lib/coffee-script/command.js:152:18
2012-05-15T19:07:42+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/hubot:109:4)
2012-05-15T19:07:42+00:00 app[web.1]:     at /app/node_modules/coffee-script/lib/coffee-script/command.js:177:29
2012-05-15T19:07:42+00:00 app[web.1]:     at Module._compile (module.js:441:26)
2012-05-15T19:07:42+00:00 app[web.1]:     at Object.run (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:79:25)
2012-05-15T19:07:42+00:00 app[web.1]:     at [object Object].<anonymous> (fs.js:123:5)
2012-05-15T19:07:42+00:00 app[web.1]:     at [object Object].emit (events.js:64:17)
2012-05-15T19:07:42+00:00 app[web.1]:     at Object.oncomplete (fs.js:1187:12)
2012-05-15T19:07:43+00:00 heroku[web.1]: Process exited with status 1
2012-05-15T19:07:43+00:00 heroku[web.1]: State changed from starting to crashed
```
